name: google_maps_cluster_manager
description: Simple Flutter clustering library for Google Maps based on Geohash.
version: 3.0.0+1
homepage: https://github.com/bpillon/google_maps_cluster_manager

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter_platform_interface: ^2.2.1
  dart_geohash: ^2.0.2

dev_dependencies:
  lint: 1.8.2
  flutter_test:
    sdk: flutter

  
